endpoints:
  restart:
    enabled: true
server:
  port: 8099
spring:
  kafka:
    bootstrap-servers: localhost:9092
    dlq:
      topic: dlq_duplicate_orders
  datasource:
    url: jdbc:mysql://localhost:3306/orders
    username: julio
    password: julio123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariOrderPool
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
